[phases.setup]
nixPkgs = ["nodejs_20", "pnpm-9_x"]

[phases.install]
cmds = [
  "pnpm install --filter @oh/db --filter @oh/api"
]

[phases.build]
cmds = [
  "pnpm --filter @oh/db prisma generate"
]

[start]
cmd = "cd packages/api && node src/index.js"
