[phases.setup]
nixPkgs = ["nodejs_20"]
aptPkgs = ["..."]

[phases.install]
cmds = [
  "corepack enable",
  "corepack prepare pnpm@9.15.9 --activate",
  "pnpm install --prod=false"
]

[phases.build]
cmds = [
  "npx prisma generate"
]

[start]
cmd = "node src/index.js"
