[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "npm install",
  "cd ../db && npm install && cd ../api"
]

[phases.build]
cmds = [
  "cd ../db && npx prisma generate && cd ../api"
]

[start]
cmd = "node src/index.js"
