[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "cd packages/db && npm install",
  "cd packages/api && npm install"
]

[phases.build]
cmds = [
  "cd packages/db && npx prisma generate"
]

[start]
cmd = "cd packages/api && node src/index.js"
