[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npx prisma db push --accept-data-loss --schema=./prisma/schema.prisma && node src/index.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
