[build]
builder = "NIXPACKS"
watchPaths = ["packages/api/**", "packages/db/**"]

[deploy]
startCommand = "cd packages/api && node src/index.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
